version: '3.1'

services:

  database:
    container_name: ${DATABASE_CONTAINER_NAME:-database}
    image: mongo:4
    restart: always
    environment:
      MONGODB_INITDB_USERNAME: "${DATABASE_USERNAME:-admin}"
      MONGODB_INITDB_PASSWORD: "${DATABASE_PASSWORD:-password}"
      DATABASE_USERNAME: "${DATABASE_USERNAME:-admin}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-password}"
      DATABASE_NAME: "${DATABASE_NAME:-database}"
    ports:
      - "${SERVICE_HOSTNAME:-127.0.0.1}:${EXPOSED_DATABASE_PORT_FIRST:-27017}-${EXPOSED_DATABASE_PORT_LAST:-27019}:27017-27019"
    expose:
      - "27017"
    volumes:
      - "./database/init/:/docker-entrypoint-initdb.d/"
