version: '3.1'

services:

  database:
    container_name: ${DATABASE_CONTAINER_NAME:-database}
    image: mongo:4
    restart: always
    environment:
      MONGODB_INITDB_USERNAME: "${DATABASE_USERNAME:-admin}"
      MONGODB_INITDB_PASSWORD: "${DATABASE_PASSWORD:-password}"
      DATABASE_USERNAME: "${DATABASE_USERNAME:-admin}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-password}"
      DATABASE_NAME: "${DATABASE_NAME:-database}"
    ports:
      - "${SERVICE_HOSTNAME:-127.0.0.1}:${EXPOSED_DATABASE_PORT_FIRST:-27017}-${EXPOSED_DATABASE_PORT_LAST:-27019}:27017-27019"
    expose:
      - "27017"
    volumes:
      - "./database/init/:/docker-entrypoint-initdb.d/"

  database-frontend:
    container_name: ${DATABASE_FRONTEND_CONTAINER_NAME:-database-frontend}
    image: mongo-express
    depends_on:
      - database
    restart: always
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
      ME_CONFIG_MONGODB_AUTH_DATABASE: "explorer-app-database"
      ME_CONFIG_BASICAUTH_USERNAME: "${DATABASE_USERNAME:-admin}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${DATABASE_PASSWORD:-password}"
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_SERVER: ${DATABASE_CONTAINER_NAME:-database}
      ME_CONFIG_OPTIONS_EDITORTHEME: "darcula"
    ports:
      - "${SERVICE_HOSTNAME:-127.0.0.1}:${EXPOSED_DATABASE_FRONTEND_PORT:-8081}:8081"
    expose:
      - "8081"
